<a href="https://colab.research.google.com/github/Gauthampharish/health-insurance/blob/main/healthinsurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [96]:
data=pd.read_csv("insurance.csv")
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values


In [97]:
print(x)
print(y)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]
[16884.92  1725.55  4449.46 ...  1629.83  2007.94 29141.36]


encoding


In [98]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))



In [99]:
print(x)

[[1.0 0.0 19 ... 0 'yes' 'southwest']
 [0.0 1.0 18 ... 1 'no' 'southeast']
 [0.0 1.0 28 ... 3 'no' 'southeast']
 ...
 [1.0 0.0 18 ... 0 'no' 'southeast']
 [1.0 0.0 21 ... 0 'no' 'southwest']
 [1.0 0.0 61 ... 0 'yes' 'northwest']]


In [101]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [102]:
print(x)

[[1.0 0.0 0.0 ... 19 27.9 'southwest']
 [0.0 1.0 0.0 ... 18 33.77 'southeast']
 [0.0 0.0 0.0 ... 28 33.0 'southeast']
 ...
 [1.0 0.0 0.0 ... 18 36.85 'southeast']
 [1.0 0.0 0.0 ... 21 25.8 'southwest']
 [1.0 0.0 0.0 ... 61 29.07 'northwest']]


In [103]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [104]:
print(x)

[[0.0 0.0 0.0 ... 0.0 19 27.9]
 [0.0 0.0 1.0 ... 1.0 18 33.77]
 [0.0 0.0 1.0 ... 1.0 28 33.0]
 ...
 [0.0 0.0 1.0 ... 0.0 18 36.85]
 [0.0 0.0 0.0 ... 0.0 21 25.8]
 [0.0 1.0 0.0 ... 0.0 61 29.07]]


training and test set

In [106]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [107]:
print(x_train)
print(y_train)

[[0.0 1.0 0.0 ... 0.0 53 26.6]
 [0.0 0.0 0.0 ... 1.0 53 21.4]
 [0.0 0.0 1.0 ... 1.0 18 37.29]
 ...
 [1.0 0.0 0.0 ... 0.0 51 34.96]
 [0.0 0.0 1.0 ... 0.0 40 22.22]
 [0.0 0.0 1.0 ... 1.0 57 27.94]]
[10355.64 10065.41  1141.45 ... 44641.2  19444.27 11554.22]


Feature scaling

In [88]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)





multiple reg


In [108]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [109]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(y_pred)
print(y_test)

[[ 4410.01  1646.43]
 [12938.43 11353.23]
 [12656.55  8798.59]
 [12925.47 10381.48]
 [  232.59  2103.08]
 [31721.7  38746.36]
 [13430.97  9304.7 ]
 [12380.22 11658.12]
 [ 3835.19  3070.81]
 [29522.25 19539.24]
 [11082.4  12629.9 ]
 [18043.59 11538.42]
 [ 9192.91  6338.08]
 [ 8038.34  7050.64]
 [ 3177.7   1137.47]
 [10967.91  8968.33]
 [ 3912.37 21984.47]
 [ 6588.    6414.18]
 [14698.11 28287.9 ]
 [14515.78 13462.52]
 [12601.66  9722.77]
 [32573.97 40932.43]
 [ 9119.71  8026.67]
 [ 9064.88  8444.47]
 [ 3060.08  2203.47]
 [ 7834.71  6664.69]
 [ 9194.47  8606.22]
 [10806.06  8283.68]
 [ 8200.33  5375.04]
 [ 4426.74  3645.09]
 [13831.22 11674.13]
 [ 6328.96 11737.85]
 [34267.58 24873.38]
 [27029.35 33750.29]
 [32988.48 24180.93]
 [ 9591.8   9863.47]
 [30468.26 36837.47]
 [27996.   17942.11]
 [15220.41 11856.41]
 [33551.75 39725.52]
 [ 6803.79  4349.46]
 [14110.04 11743.93]
 [10362.84 19749.38]
 [14783.88 12347.17]
 [ 4703.17  4931.65]
 [13174.27 30260.  ]
 [ 4006.53 27724.29]
 [28653.59 34

In [111]:
import sklearn.metrics as sm
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_pred), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_pred), 2)) 
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_pred), 2)) 
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2)) 
print("R2 score =", round(sm.r2_score(y_test, y_pred), 2))

Mean absolute error = 4054.15
Mean squared error = 35349546.2
Median absolute error = 2249.14
Explain variance score = 0.76
R2 score = 0.76
