<a href="https://colab.research.google.com/github/Gauthampharish/health-insurance/blob/main/healthinsurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [36]:
data=pd.read_csv("insurance.csv")
x=data.iloc[:,0:1].values
y=data.iloc[:,-1].values


In [37]:
print(x)


[[19]
 [18]
 [28]
 ...
 [18]
 [21]
 [61]]


In [44]:
data.size

9366

encoding


In [38]:
print(y)

[16884.92  1725.55  4449.46 ...  1629.83  2007.94 29141.36]


training and test set

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [40]:
print(x_train)
print(y_train)

[[53]
 [53]
 [18]
 ...
 [51]
 [40]
 [57]]
[10355.64 10065.41  1141.45 ... 44641.2  19444.27 11554.22]


Feature scaling

multiple reg


In [41]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [42]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(y_pred)
print(y_test)

[[ 7982.6   1646.43]
 [17950.64 11353.23]
 [16376.74  8798.59]
 [15852.1  10381.48]
 [ 8507.23  2103.08]
 [11130.4  38746.36]
 [15852.1   9304.7 ]
 [17688.32 11658.12]
 [10081.13  3070.81]
 [12704.3  19539.24]
 [18737.59 12629.9 ]
 [17163.69 11538.42]
 [13228.94  6338.08]
 [14015.89  7050.64]
 [ 7720.28  1137.47]
 [15589.79  8968.33]
 [11655.03 21984.47]
 [12179.67  6414.18]
 [18475.27 28287.9 ]
 [19262.22 13462.52]
 [16639.06  9722.77]
 [10868.08 40932.43]
 [15065.15  8026.67]
 [16114.42  8444.47]
 [ 7720.28  2203.47]
 [13753.57  6664.69]
 [14278.2   8606.22]
 [15589.79  8283.68]
 [11655.03  5375.04]
 [10868.08  3645.09]
 [17688.32 11674.13]
 [11917.35 11737.85]
 [16901.37 24873.38]
 [ 7982.6  33750.29]
 [15589.79 24180.93]
 [16901.37  9863.47]
 [10868.08 36837.47]
 [ 8507.23 17942.11]
 [18212.96 11856.41]
 [14802.84 39725.52]
 [10343.45  4349.46]
 [18212.96 11743.93]
 [16114.42 19749.38]
 [18475.27 12347.17]
 [11130.4   4931.65]
 [18737.59 30260.  ]
 [ 8244.92 27724.29]
 [10343.45 34

In [43]:
import sklearn.metrics as sm
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_pred), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_pred), 2)) 
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_pred), 2)) 
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2)) 
print("R2 score =", round(sm.r2_score(y_test, y_pred), 2))

Mean absolute error = 9070.62
Mean squared error = 137488743.05
Median absolute error = 6596.21
Explain variance score = 0.08
R2 score = 0.08
